### ISSUE TITLE
escape doesn't close the tooltip

### ISSUE THREAD

**Issue by idoros** [ZoeBijl/apg-tooltip#1]
Seems like a the `close` function was changed to `closeTooltip` and the reference within the [globalEscape](https://github.com/ZoeBijl/apg-tooltip/blob/38a2f8713eb99c86a29c17e1125d266c99ea846c/tooltips.js#L55) was not updated

**Comment by ZoeBijl** [comment]
Ah good catch! Thank you, I’ll fix it. This also applies to `globalPointerDown`.

**Comment by ZoeBijl** [comment]
Fixed 🎉
